import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { WhatsAppWidget } from 'react-whatsapp-widget'
import 'react-whatsapp-widget/dist/index.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Whatsapp widget app
        <WhatsAppWidget phoneNumber="27832459000" message="Hello! 👋🏼 What can we do for you?" />
      </main>

      
    </div>
  )
}
